import { Inter } from "next/font/google";
import "./globals.css";

import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";

import Layout from "@/components/applayout/layout.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <MantineProvider>
          <Layout>{children}</Layout>
        </MantineProvider>
      </body>
    </html>
  );
}
